- name: Criar Security Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: SG Ansible
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
#regra de saida        
    rules_egress: 
    - proto: all
      cidr_ip: 0.0.0.0/0  
  register: basic_firewall

- name: Criar instancia ec2
  local_action: ec2
    group={{ sec_group_name }}
    instance_type={{ instance_type }}
    image={{ image }}
    profile={{ profile }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Adiconar instancia ao inventario temporario
  add_host: name={{ item.public_ip }} groups=instancias-net
  with_items: "{{ ec2.instances }}"


- name: Adiciona o IP publico da instancia criada ao arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[instancias]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Adiciona o IP privado da instancia criada ao arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.private_ip }}
    insertafter="[instancias]" line={{ item.private_ip }}
  with_items: "{{ ec2.instances }}"

- name: Aguarda o SSH para validar que a instancia foi criada
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"  

- name: Adiciona tag na instancia e adiciona o Nome da instancia
  local_action: ec2_tag resource={{ item.id }} region={{ region }} profile={{ profile }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: ansible-{{ item.ami_launch_index|int + 1 }}